from __future__ import annotations

# Map of ECO codes to human-readable opening names.
# Not every one of the ~500 codes is listed; anything missing falls back to a
# volume-based description via ``eco_name``.
ECO_NAMES: dict[str, str] = {
    "A00": "Uncommon Opening",
    "A01": "Nimzo-Larsen Attack",
    "A02": "Bird's Opening",
    "A03": "Bird's Opening",
    "A04": "Réti Opening",
    "A05": "Réti Opening",
    "A06": "Réti Opening",
    "A07": "King's Indian Attack",
    "A08": "King's Indian Attack",
    "A09": "Réti Opening",
    "A10": "English Opening",
    "A11": "English, Caro-Kann Defensive System",
    "A13": "English Opening",
    "A15": "English, Anglo-Indian Defense",
    "A20": "English, King's English Variation",
    "A40": "Queen's Pawn Game",
    "A45": "Queen's Pawn Game",
    "A46": "Queen's Pawn Game",
    "A48": "London System",
    "A50": "Queen's Pawn Game",
    "A56": "Benoni Defense",
    "A57": "Benko Gambit",
    "A80": "Dutch Defense",
    "A84": "Dutch Defense",
    "B00": "Uncommon King's Pawn Opening",
    "B01": "Scandinavian Defense",
    "B02": "Alekhine Defense",
    "B03": "Alekhine Defense",
    "B06": "Modern Defense",
    "B07": "Pirc Defense",
    "B08": "Pirc Defense",
    "B10": "Caro-Kann Defense",
    "B12": "Caro-Kann Defense",
    "B13": "Caro-Kann, Exchange Variation",
    "B18": "Caro-Kann, Classical Variation",
    "B20": "Sicilian Defense",
    "B21": "Sicilian, Smith-Morra Gambit",
    "B22": "Sicilian, Alapin Variation",
    "B23": "Sicilian, Closed",
    "B27": "Sicilian Defense",
    "B30": "Sicilian Defense",
    "B32": "Sicilian Defense",
    "B33": "Sicilian, Sveshnikov Variation",
    "B40": "Sicilian Defense",
    "B44": "Sicilian Defense",
    "B50": "Sicilian Defense",
    "B54": "Sicilian, Najdorf-related",
    "B70": "Sicilian, Dragon Variation",
    "B76": "Sicilian, Dragon, Yugoslav Attack",
    "B80": "Sicilian, Scheveningen Variation",
    "B90": "Sicilian, Najdorf Variation",
    "C00": "French Defense",
    "C01": "French, Exchange Variation",
    "C02": "French, Advance Variation",
    "C03": "French, Tarrasch Variation",
    "C10": "French, Paulsen Variation",
    "C11": "French Defense",
    "C15": "French, Winawer Variation",
    "C20": "King's Pawn Game",
    "C21": "Center Game",
    "C23": "Bishop's Opening",
    "C25": "Vienna Game",
    "C30": "King's Gambit",
    "C33": "King's Gambit Accepted",
    "C40": "King's Knight Opening",
    "C41": "Philidor Defense",
    "C42": "Petrov's Defense",
    "C44": "King's Pawn Game",
    "C45": "Scotch Game",
    "C46": "Three Knights Opening",
    "C47": "Four Knights Game",
    "C50": "Italian Game",
    "C51": "Evans Gambit",
    "C53": "Italian Game, Classical",
    "C55": "Italian Game, Two Knights Defense",
    "C57": "Italian, Two Knights, Fried Liver",
    "C60": "Ruy Lopez",
    "C63": "Ruy Lopez, Schliemann Defense",
    "C65": "Ruy Lopez, Berlin Defense",
    "C67": "Ruy Lopez, Berlin Defense",
    "C68": "Ruy Lopez, Exchange Variation",
    "C77": "Ruy Lopez, Morphy Defense",
    "C84": "Ruy Lopez, Closed",
    "C88": "Ruy Lopez, Closed",
    "C89": "Ruy Lopez, Marshall Attack",
    "D00": "Queen's Pawn Game",
    "D02": "London System",
    "D04": "Queen's Pawn Game",
    "D06": "Queen's Gambit",
    "D07": "Queen's Gambit Declined, Chigorin Defense",
    "D10": "Slav Defense",
    "D15": "Slav Defense",
    "D20": "Queen's Gambit Accepted",
    "D30": "Queen's Gambit Declined",
    "D35": "Queen's Gambit Declined, Exchange",
    "D37": "Queen's Gambit Declined",
    "D43": "Semi-Slav Defense",
    "D45": "Semi-Slav Defense",
    "D50": "Queen's Gambit Declined",
    "D60": "Queen's Gambit Declined, Orthodox",
    "D70": "Neo-Grünfeld Defense",
    "D80": "Grünfeld Defense",
    "D85": "Grünfeld, Exchange Variation",
    "D90": "Grünfeld Defense",
    "E00": "Catalan Opening",
    "E01": "Catalan Opening",
    "E10": "Queen's Pawn Game",
    "E11": "Bogo-Indian Defense",
    "E12": "Queen's Indian Defense",
    "E15": "Queen's Indian Defense",
    "E20": "Nimzo-Indian Defense",
    "E32": "Nimzo-Indian, Classical",
    "E40": "Nimzo-Indian, Rubinstein",
    "E60": "King's Indian Defense",
    "E70": "King's Indian Defense",
    "E80": "King's Indian, Sämisch Variation",
    "E90": "King's Indian Defense",
    "E97": "King's Indian, Orthodox Variation",
}


def _volume_hint(code: str) -> str:
    letter = code[:1].upper()
    return {
        "A": "Flank / irregular opening",
        "B": "Semi-Open Game (non-1…e5)",
        "C": "Open Game / French",
        "D": "Closed & Queen's Gambit",
        "E": "Indian Defences",
    }.get(letter, "")


def eco_name(code: str | None) -> str:
    """Return a plain-text opening name for an ECO ``code``.

    Falls back to a volume description (or an empty string) when the exact
    code is not known.
    """
    if not code:
        return ""
    code = code.strip().upper()
    if code in ECO_NAMES:
        return ECO_NAMES[code]
    return _volume_hint(code)
